### ISSUE TITLE
spring boot configuration annotation processor not found in classpath

### ISSUE THREAD

**Issue by JayvinPan** [spring-projects/gradle-plugins#60]
I saw this problem you had solve at stackoverflow. I add propdeps-plugin at build file but it doesn't work for me. The version of my idea is 2017.1 and gradle is 3.5.1(the original version that I used is 4.0).

**Comment by wilkinsona** [comment]
It sounds like you're trying to to report a problem with the propdeps plugin. It's now managed in a separate repository: https://github.com/spring-gradle-plugins/propdeps-plugin. Please open an issue there with a small sample that reproduces your problem, a description of the expected behaviour, and a description of the actual behavioir
